name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1
      id: test1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test1
        setup-command: ''
        command: make test1
        timeout: 10
        max-score: 1
    - name: Test2
      id: test2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test2
        setup-command: ''
        command: make test2
        timeout: 10
        max-score: 1
    - name: Test3
      id: test3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test3
        setup-command: ''
        command: make test3
        timeout: 10
        max-score: 1
    - name: Test4
      id: test4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test4
        setup-command: ''
        command: make test4
        timeout: 10
        max-score: 2
    - name: Test5
      id: test5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test5
        setup-command: ''
        command: make test5
        timeout: 10
        max-score: 2
    - name: Test6
      id: test6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test6
        setup-command: ''
        command: make test6
        timeout: 10
        max-score: 2
    - name: Test7
      id: test7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test7
        setup-command: ''
        command: make test7
        timeout: 10
        max-score: 2
    - name: Test8
      id: test8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test8
        setup-command: ''
        command: make test8
        timeout: 10
        max-score: 3
    - name: Test9
      id: test9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test9
        setup-command: ''
        command: make test9
        timeout: 10
        max-score: 3
    - name: Test10
      id: test10
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test10
        setup-command: ''
        command: make test10
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
        TEST4_RESULTS: "${{steps.test4.outputs.result}}"
        TEST5_RESULTS: "${{steps.test5.outputs.result}}"
        TEST6_RESULTS: "${{steps.test6.outputs.result}}"
        TEST7_RESULTS: "${{steps.test7.outputs.result}}"
        TEST8_RESULTS: "${{steps.test8.outputs.result}}"
        TEST9_RESULTS: "${{steps.test9.outputs.result}}"
        TEST10_RESULTS: "${{steps.test10.outputs.result}}"
      with:
        runners: test1,test2,test3,test4,test5,test6,test7,test8,test9,test10
